In [488]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

In [489]:
%cd gdrive/MyDrive/Adaboost/

[Errno 2] No such file or directory: 'gdrive/MyDrive/Adaboost/'
/content/gdrive/MyDrive/Adaboost

In [490]:
!pip install numpy scikit-learn pandas matplotlib

Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (1.19.5)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.7/dist-packages (1.0.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (1.1.5)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.7/dist-packages (3.2.2)
Requirement already satisfied: scipy>=1.1.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn) (1.4.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from scikit-learn) (3.0.0)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.7/dist-packages (from scikit-learn) (1.1.0)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas) (2018.9)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.7/dist-packages (from matplotlib) (0.11.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib) (3.0.6)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.7/dist-packages (from matplotlib) (1.3.2)

In [491]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import math
import random

In [492]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import seaborn as sns
from matplotlib import pyplot as plt
%matplotlib inline

from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import minmax_scale, StandardScaler, MinMaxScaler
from sklearn import preprocessing
from sklearn.model_selection import train_test_split

In [493]:
def preprocess1():
  dataset = pd.read_csv('WA_Fn-UseC_-Telco-Customer-Churn.csv')

  dataset.drop(['customerID'] , inplace=True , axis='columns')

  for i in dataset.columns:
    #print(i, dataset[i].nunique())
    if(dataset[i].nunique() == 2 and dataset[i].dtype == 'object'):
      #print(dataset[i].unique()[0], dataset[i].unique()[1])
      dataset[i] = dataset[i].map({dataset[i].unique()[0] : 0, dataset[i].unique()[1] : 1})

  dataset['TotalCharges'] = pd.to_numeric(dataset['TotalCharges'], errors='coerce')

  # mean = dataset['TotalCharges'].mean()
  # dataset['TotalCharges'] = dataset['TotalCharges'].replace([np.nan],mean)
  arr = []
  for i in range(len(dataset['tenure'])):
    if(dataset.loc[i , 'tenure'] == 0):
      imagined_tenure = random.random()
      # print(imagined_tenure)
      # print(dataset.loc[i , ['MonthlyCharges']])
      the_loc = dataset.loc[i , ['MonthlyCharges']]
      # print(the_loc)
      dataset.at[i , ['TotalCharges']] = float(the_loc * imagined_tenure)
      # print(dataset.loc[i , ['TotalCharges']])
      arr.append(i)
  #dataset.info()
  # for i in dataset['TotalCharges']:
  #   if(np.isnan(i)):
  #     i.replace(mean)

  dataset['Churn'] = dataset['Churn'].map({1: 1, 0: -1})
  print(dataset['Churn'].unique())


  dataset = pd.get_dummies(dataset)
  #print(dataset.head())

  return dataset


def normalize(dataset):
  for i in dataset.columns:
    if(dataset[i].nunique()>2):
      dataset[i] = (dataset[i]-dataset[i].min())/(dataset[i].max()-dataset[i].min())
  return dataset

#dataset = normalize(dataset)



#dataset = dataset[1000:3050]
# dataset.head(100)

#dataset['TotalCharges'].count()

#pd.Index(dataset['Churn']).value_counts()

In [494]:
# dataset.at[0, ['tenure']] = 0.2
# dataset.loc[0 , ['tenure']]
# arr = []
# for i in range(len(dataset['tenure'])):
#   if(dataset.loc[i , 'tenure'] == 0):
#     imagined_tenure = random.random()
#     dataset.at[i , ['TotalCharges']] = dataset.loc[i , ['MonthlyCharges']] * imagined_tenure
#     arr.append(i)
# dataset.loc[488 ,['TotalCharges']]

In [495]:
def preprocess2():
  dataset = pd.read_csv('adult.csv')


  # print(dataset.iloc[27])

  for i in dataset.columns:
    max_frequent_value = dataset[i].value_counts().idxmax()
    dataset[i] = dataset[i].replace(' ?', max_frequent_value)

  # print(dataset.iloc[27])

  dataset[' Income'] = dataset[' Income'].map({' <=50K': (-1), ' >50K': (1)})
  for i in dataset.columns:
    #print(i, dataset[i].nunique())
    if(dataset[i].nunique() == 2 and dataset[i].dtype == 'object'):
      #print(dataset[i].unique()[0], dataset[i].unique()[1])
      dataset[i] = dataset[i].map({dataset[i].unique()[0] : 0, dataset[i].unique()[1] : 1})

  # for i in dataset.columns:
  #   if(dataset[i].nunique() == 2):
  #     print(i)
  #     print(dataset[i].unique())
  
  # print(dataset['Churn'].unique())

  #dataset.info()

  dataset = pd.get_dummies(dataset)

  # for col in dataset.columns:
  #   for j in dataset[col]:
  #     if np.isnan(j) :
  #       print(j)


  print(dataset.count().unique())
  return dataset

adult_df = preprocess2()
x = adult_df.drop([' Income'], axis='columns')
y = adult_df[' Income']




# dataset = preprocess1()
# x = dataset.drop(['Churn'], axis='columns')
# y = dataset['Churn']

x
y

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

arr = x_test.to_numpy()

# print(arr)

print('nan paisi data te ',np.any(np.isnan(arr)))


x_train = normalize(x_train)
x_test = normalize(x_test)

arr = x_test.to_numpy()

print('nan paisi data te ',np.any(np.isnan(arr)))

x_test

[32561]
nan paisi data te  False
nan paisi data te  False

            age  ...   native-country_ Yugoslavia
22278  0.136986  ...                            0
8950   0.136986  ...                            0
7838   0.109589  ...                            0
16505  0.397260  ...                            0
19140  0.383562  ...                            0
...         ...  ...                          ...
7694   0.273973  ...                            0
10410  0.150685  ...                            0
1043   0.369863  ...                            0
30860  0.493151  ...                            0
12467  0.410959  ...                            0

[6513 rows x 104 columns]

In [496]:
# x = dataset.drop(['Churn'], axis='columns')

# y = dataset['Churn']

# # x
# # y

# x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

# x_train = normalize(x_train)
# x_test = normalize(x_test)

x_train_matrix = x_train.values
x_test_matrix = x_test.values
y_train_matrix = y_train.values.reshape(-1,1)
y_test_matrix = y_test.values.reshape(-1,1)

print('nan paisi x tr te ',np.any(np.isnan(x_train_matrix)))
print('nan paisi y tr te ',np.any(np.isnan(y_train_matrix)))
print('nan paisi X tst te ',np.any(np.isnan(x_test_matrix)))
print('nan paisi t tst te ',np.any(np.isnan(y_test_matrix)))


print(type(x_train_matrix))
x_test_matrix.shape

nan paisi x tr te  False
nan paisi y tr te  False
nan paisi X tst te  False
nan paisi t tst te  False
<class 'numpy.ndarray'>

(6513, 104)

In [497]:
y_test_matrix[3][0]

-1

In [498]:
def Tanh(z):
    th = np.tanh(z)
    # if(np.isnan(th)):
    #   if(z < 0):
    #     return -1
    #   else:
    #     return 1

    return th

In [499]:
def hypothesistanh(theta,x):
    #print ('theta ', theta)	
    # z = 0
    # for i in range(len(theta)):
    #     xi = x[i]
    #     z += np.dot(xi,theta[i].transpose())

    #z = np.dot(x,theta)
    z = x @ theta
    # print('z.shape',z.shape)
    return Tanh(z)

In [500]:
def mean_error(y , y_hat):
  diff = y - y_hat
  return np.mean(np.power(diff , 2))

In [501]:
def gradient_descent(X, y, y_hat, lr):
    m = X.shape[0]
    #dw = (1/m) * ( X.T @ ((y - y_hat) * (1 - y_hat**2)) )
    
    diff = y - y_hat
    derivative = 1 - np.power(y_hat , 2)
    multi = diff * derivative
    # print('multi: ', multi.shape)
    # print('derivative: ', derivative.shape)
    # print('diff: ', diff.shape)

    #dw = np.dot(X.T , multi)
    dw = X.T @ multi
    # print('dw: ', dw.shape)
    constant = (1/float(m)) * float(lr) 
    return constant * dw

In [502]:
def log_reg(X, y, iterations, lr, threshold):
  m,n = X.shape

  w = np.zeros((n+1 , 1))
  # print(w.shape)

  X_train = np.concatenate((np.ones((m, 1)), X), axis=1)


  errors = []

  for i in range(iterations):
    y_hat = hypothesistanh(w , X_train)
    # print('y_hat' , y_hat.shape)

    decay = gradient_descent(X_train , y , y_hat , lr)

    if(np.isnan(decay.any())):
      print('decay')
    # print('decay :' , decay.shape)

    # print('w_before :' , w.shape)
    w = w + decay
    # print('w_after :' , w.shape)

    error = mean_error(y , y_hat)
    errors.append(error)

    # if error < threshold:
    #   print('bingo', i)
    #   break

  # print(w.shape)
  score = 0
  length = x_test_matrix.shape[0]
  X_test = np.concatenate((np.ones((length, 1)), x_test_matrix), axis=1)
  #print(X_test)
  # print('X_test.shape : ' , X_test.shape)
  # print('w.shape : ' , w.shape)
  print('nan paisi w te ',np.any(np.isnan(w)))
  print('nan paisi X te ',np.any(np.isnan(X_test)))
  prediction = hypothesistanh(w, X_test)
  # for i in range(prediction.shape[0]):
  #   if(np.isnan(prediction[i].any())):
  #       print('decay')

  print('nan paisi',np.any(np.isnan(prediction)))

  # print(prediction)
  #print('pred uniq ', np.unique(prediction, axis=0))
  
  for i in range(length):
    #X_test[i] = X_test[i].reshape(1,-1)
    #print(X_test[i].shape)
    #prediction = hypothesistanh(w, X_test[i])
    # print(prediction.shape)
    if prediction[i][0] < 0:
      prediction[i][0] = -1
    else:
      prediction[i][0] = 1
    # if(prediction == -1):
    #   print("prediction ", prediction)
    answer = y_test_matrix[i][0]
    if prediction[i][0] == answer:
      score += 1

  #print('pred uniq ', np.unique(prediction, axis=0))
  my_score = float(score) / float(length)
  print ('Your score with tanh: ', my_score)
  
  #print(w)
  return w

In [503]:
# alpha = 0.1
# iterations = 100
# threshold = 0.5
# w = log_reg(x_train_matrix , y_train_matrix , iterations , alpha , threshold)

In [504]:
# a = np.array([[1,2],[2,3]])
# b = np.array([4,5])
# a.shape
# c = a @ b
# np.concatenate((np.ones((x_train_matrix.shape[0], 1)),x_train_matrix), axis=1)

In [505]:
def cost_function_derivativetanh(x_train,y_train,theta,j,m,alpha):
    sumErrors = 0
    for i in range(m):
        xi = x_train.iloc[i]
        hi = hypothesistanh(theta,xi)
        yt = y_train.iloc[i]
        hit = np.subtract((float)(hi),float(yt))
        error = np.dot(hit,x_train.iloc[i][j])
        error = np.dot(error,(1-hi*hi))
        sumErrors += error
    #m = len(y_test)
    constant = float(alpha)/float(m)
    j = constant * sumErrors
    #print("SumErrors", sumErrors)
    return j

In [506]:
def gradient_descenttanh(x_train,y_train,theta,m,alpha):
    new_theta = []
    for j in range(len(theta)):
        new_theta_value = theta[j] - cost_function_derivativetanh(x_train,y_train,theta,j,m,alpha)
        new_theta.append(new_theta_value)
    #print ('theta ', new_theta)	
    return new_theta

In [507]:
def error_calc(x_train,y_train,theta):
  total = 0
  m = len(y_train)
  for i in range(m):
        xi = x_train.iloc[i]
        hi = hypothesistanh(theta,xi)
        yt = y_train.iloc[i]
        hit = np.subtract((float)(hi),float(yt))
        total += hit*hit

  return total/float(m)

In [508]:
len(x_test)

6513

In [509]:
def logistic_regression_tanh(x_train,y_train,alpha,theta,num_iters, threshold):
    m = len(y_train)
    for x in range(num_iters):
        new_theta = gradient_descenttanh(x_train,y_train,theta,m,alpha)
        theta = new_theta
        total = error_calc(x_train,y_train,theta)
        if(total < threshold):
          break
        #if x % 1000 == 0:
            #cost_functiontanh(theta,m)
        #print ('theta ', theta)
        #print('total' , total)	
            #print ('cost is ', cost_functiontanh(theta,m))
    score = 0
    length = len(x_test)
    for i in range(length):
        prediction = hypothesistanh(theta,x_test.iloc[i])
        
        if prediction < 0:
          prediction = -1
        else:
          prediction = 1
        # if(prediction == -1):
        #   print("prediction ", prediction)
        answer = y_test.iloc[i]
        if prediction == answer:
            score += 1
    my_score = float(score) / float(length)
    print ('Your score with tanh: ', my_score)

    return theta

In [510]:
def ada_boost(num_iter):
  m = y_train_matrix.shape[0]

  weight = np.empty(m)
  weight.fill(1.0/float(m))
  #print(weight)
  
  hypothesis_container = []
  hypothesis_weight = []

  np.random.seed(5)

  x_train_sampled = np.copy(x_train_matrix)
  # x_train_sampled_2 = np.concatenate((np.ones((m, 1)), x_train_matrix), axis=1)
  y_train_sampled = np.copy(y_train_matrix)

  for i in range(num_iter):
    
    resampled_int = np.random.choice(x_train_matrix.shape[0], size=m, p=weight)
    # print(resampled_int)
    x_train_sampled = x_train_matrix[resampled_int , :]
    y_train_sampled = y_train_matrix[resampled_int , :]
    #print(temp)
    #print(y_train_sampled)
    
    theta = log_reg(np.copy(x_train_sampled), y_train_sampled, iterations , alpha, 0.5)
    #hypothesis_container.append(theta)
    #print(theta.shape)
    #print(theta)

    error = 0

    x_train_sampled_2 = np.concatenate((np.ones((m, 1)), x_train_sampled), axis=1)
    #print(x_train_sampled_2)

    h = hypothesistanh(theta , x_train_sampled_2)
    #print('go4')
    for j in range(m):
      #xj = x_train_sampled.iloc[j]
      #h = hypothesistanh(theta,xj)
      if h[j][0] < 0:
        h[j][0] = -1
      else:
        h[j][0] = 1
      yj = y_train_sampled[j][0]
      if h[j][0] != yj:
        error = error + weight[j]

    # if error > 0.5:
    #   #print(error)
    #   continue

    h = hypothesistanh(theta , x_train_sampled_2)
    for j in range(m):
      # xj = x_train_sampled.iloc[j]
      # hj = hypothesistanh(theta,xj)
      if h[j][0] < 0:
        h[j][0] = -1
      else:
        h[j][0] = 1
      yj = y_train_sampled[j][0]
      if h[j][0] == yj:
        weight[j] = weight[j] * float(error)/(1.0-float(error))

    weight = weight/np.sum(weight)
    #print(weight)

    hypothesis_container.append(theta)
    hypothesis_weight.append(np.log2(  (1.0-float(error))   /   float(error)   ))

  
  X_test = np.concatenate((np.ones((x_test_matrix.shape[0], 1)), x_test_matrix), axis=1)
  #print('go')

  h_cap = Weighted_majority(X_test , hypothesis_container , hypothesis_weight)
  #print(h_cap)
  #print('go2')

  m2 = len(x_test)
  score = 0
  for i in range(m2):
    if h_cap[i] < 0:
      h_cap[i] = -1
    else:
      h_cap[i] = 1

    answer = y_test_matrix[i][0]
    if h_cap[i] == answer:
      score += 1
  # print(h_cap)
  # print(np.unique(h_cap))
  print(float(score) / float(m2))


def Weighted_majority(x , hypothesis_container , hypothesis_weight):
  m = len(x)
  iter = len(hypothesis_weight)
  #print(iter)
  h_cap = np.zeros(m)
  for k in range(iter):
    h = hypothesistanh(hypothesis_container[k].reshape(-1, 1), x)
    for i in range(m):
      
      mul = h[i][0]*hypothesis_weight[k]
      h_cap[i] = h_cap[i] + mul

  #print(h_cap)
  return h_cap

In [511]:
initial_theta = np.zeros(x_test.iloc[1].shape)
#x_test.iloc[1]
alpha = 0.5
iterations = 1000
#logistic_regression_tanh(alpha,initial_theta,iterations)
ada_boost(5)

nan paisi w te  False
nan paisi X te  False
nan paisi False
Your score with tanh:  0.8340242591739597
nan paisi w te  False
nan paisi X te  False
nan paisi False
Your score with tanh:  0.8352525717795178
nan paisi w te  False
nan paisi X te  False
nan paisi False
Your score with tanh:  0.8303393213572854
nan paisi w te  False
nan paisi X te  False
nan paisi False
Your score with tanh:  0.833256563795486
nan paisi w te  False
nan paisi X te  False
nan paisi False
Your score with tanh:  0.8303393213572854
0.8355596499309074

In [512]:
# bal = np.array([])
# counter = 0
# abal = [1,2,3,4,5]
# dhon = [3,4,6,7,8,9]
# bal.append(abal)
# bal.append(dhon)
# len(bal[1])
# bal = np.empty(5)
# bal.fill(1/5)
# bal
# len(y_train)
# ada_boost(3)
a = np.array([[1, 0],
              [0, 1]])

a[0]

array([1, 0])

In [513]:
a = [1,2,3,4,5]
b = [1,2,3,4,5]
c = np.dot(a,b)
c

55